[default]

[development]
DB_NAME = "mtdev"
DB_USER = "admin"
DB_HOST = "localhost"
DB_PORT = "5432"

[production]

[testing]
DB_NAME = "mttest"
DB_USER = "admin"
DB_HOST = "localhost"
DB_PORT = "5432"